version: '3.7'

services:

  backend:
    build: ./server
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.uas-backend.entrypoints=websecure"
      - "traefik.http.routers.uas-backend.rule=HOST(`$VIRTUAL_HOST`) && PathPrefix(`/api/`, `/auth/`)"
      - "traefik.http.services.uas-backend.loadbalancer.server.port=4664"
    environment:
      DB_TYPE: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - traefik
      - backend
    logging:
        driver: "local"
        options:
            max-size: "10m"
            max-file: "5"

  frontend:
    build: ./client
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.uas-frontend.entrypoints=websecure"
      - "traefik.http.routers.uas-frontend.rule=HOST(`$VIRTUAL_HOST`)"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - traefik
      - backend
    logging:
        driver: "local"
        options:
            max-size: "10m"
            max-file: "5"

  db:
    image: mariadb:10.2
    restart: unless-stopped
    networks:
      - backend
    volumes: 
      - ./docker-data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

networks:
  backend:
  traefik:
    external: true