---
name: Release Docker

on:
  push:
    tags:
      - "*" # triggers only if push new tag version
  workflow_dispatch:

env:
  IMAGE_NAME_PREFIX: maadmin-

jobs:
  docker-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context: [ "backend" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with: # https://github.com/docker/build-push-action/issues/761#issuecomment-1383822381
          driver-opts: |
            image=moby/buildkit:v0.10.6
      - name: Set up QEMU for multiple platforms
        uses: docker/setup-qemu-action@master
        with:
          platforms: arm64,amd64
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-${{ matrix.context }}
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME_PREFIX }}${{ matrix.context }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=develop
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ${{ matrix.context }}/
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache-${{ matrix.context }}
          cache-to: type=local,dest=/tmp/.buildx-cache-${{ matrix.context }}-new
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
      - name: Prepare cache for next build
        run: |
          rm -rf /tmp/.buildx-cache-${{ matrix.context }}
          mv /tmp/.buildx-cache-${{ matrix.context }}-new /tmp/.buildx-cache-${{ matrix.context }}
